.eslintrc.js, .storybook/main.js, package.json, src/components/TextInput.stories.tsx, src/components/TextInput.tsx, tailwind.config.js, yarn.lock
Just an input. Based off the react-uswds [`TextInput`](https://github.com/trussworks/react-uswds/blob/3934ecd3db1b4ac58fa0fdbcdd5d34a4e6c09ddf/src/components/forms/TextInput/TextInput.tsx) implementation but with CFPB styles.
I also installed the storybook accessibility add-on that provides a tab with automated a11y tests. And I cleaned up the insanely opinionated eslint config file a bit.
1. Pull down branch.
2. `yarn && yarn start`
3. Visit http://localhost:6006/?path=/story/components-textinput--default
4. It should behave similarly to our standard [single-line text inputs](https://cfpb.github.io/design-system/components/text-inputs).
See https://github.local/reg-tech/sbl-data-collection/issues/374
=> Add text input component and stories

src/components/Checkbox.stories.tsx, src/components/Checkbox.tsx, src/components/Label.stories.tsx, src/components/Label.tsx, src/components/Radio.stories.tsx, src/components/Radio.tsx
Adds some label, checkbox and radio button components.
1. Pull down branch.
2. `yarn && yarn start`
3. View the [checkbox](http://localhost:6006/?path=/story/components-checkbox--default-checkbox) and [radio](http://localhost:6006/?path=/story/components-radio--default-radio) stories
4. They should look similar to the DS [checkboxes](https://cfpb.github.io/design-system/components/checkboxes) and [radios](https://cfpb.github.io/design-system/components/radio-buttons)
See https://github.local/reg-tech/sbl-data-collection/issues?q=is%3Aissue+label%3A%22Design+System
=> Add Label/Checkbox/Radio components

src/components/Icon.tsx, src/hooks/useIconSvg.tsx
Puts the dynamic import path for the icons directly in the "import" statement.
Previously we saw that the icons, though displayed correctly when running locally, were not correctly bundled or displayed in the Netlify deployments.  
As shown in this [PR's preview deployment](https://deploy-preview-8--cfpb-design-stories.netlify.app/?path=/docs/components-icon--icon), the icons now display correctly.
=> [Fix][Component] Icon - dynamic asset import

.eslintrc.js, src/components/Expandable.stories.tsx, src/components/Expandable.tsx, src/components/ExpandableGroup.stories.tsx, src/components/ExpandableGroup.tsx
Component has been refactored to leverage the CFPB Design System's `Expandable` controller, allowing us to eliminate any state management for tracking expanded/collapsed status.
- eslint: Disable unicorn/no-null which doesn't make sense in React components which need to return null when not rendering elements
- fix: cleanup eslint errors
- fix: Some animation for show/hide of Expandable.
- fix: Hide other expandables when opening an Accordion
=> 400 expandable

src/components/Banner.less, src/components/Banner.stories.tsx, src/components/Banner.test.tsx, src/components/Banner.tsx, src/components/BannerLanguageLink.tsx, src/components/Dropdown.tsx, src/components/Tagline.stories.tsx, src/components/Tagline.test.tsx, src/components/Tagline.tsx, src/components/header.css, src/types/jsxElement.ts
Closes #27 
- Implements CFPB DS global eyebrow
- Adapts their .less styles (couldn't access .less variables or use functions such as unit())
- Adds stories, tests
1. git checkout banner && yarn 
2. yarn test
3. yarn start -> click around
=> Banner (Global Eyebrow)

package.json, src/components/Dropdown.stories.tsx, src/components/Dropdown.tsx, src/components/DropdownPills.tsx, src/components/Label.tsx, src/types/untyped.d.ts, yarn.lock
Closes #28 
Improves keyboard accessibility by making `Tab` act as one might expect.
- Tab / Shift + Tab will navigate the dropdown instead of selecting the highlighted option
- Moves DropdownPills into new file to clean up Dropdown.tsx
- Adds a story for Multiselect w/ Default Value
- Cleans up some variable naming in Label.tsx
2. Open http://localhost:6006/?path=/story/components-dropdown--multi-select
3. Click to open menu
4. Hit `Tab` / `Shift + Tab` to move down/up option list
5. Hit `Escape` > `Tab` to navigate away from Dropdown
=> Multiselect Dropdown - Tab to navigate instead of select

package.json, src/components/Dropdown.test.tsx, src/components/Dropdown.tsx, src/components/DropdownPills.test.tsx, src/components/DropdownPills.tsx, yarn.lock
Closes #34 
~~This builds on https://github.com/cfpb/design-stories/pull/46, so I will leave this in `Draft` until that gets merged.~~
- React Testing Library tests for Dropdown and supporting components
2. Observe all tests pass
I have tried applying many different types to the `useRef` that gets passed to the `<Select />` in an attempt to fix the notifications such as `Property 'focusOption' does not exist on type 'never'`.  I have also tried type casting calls to `selectReference.current` but no luck on identifying at which type level these methods/properties are defined.
I've disabled the ESLint rules that I could on those lines but what remains is un-disableable. 
A few instances of wrapped actions seem to fail to update the `render`ed DOM, so subsequent …
=> [Tests] Dropdown

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/DropdownPills.less, src/components/Dropdown/DropdownPills.tsx
[Short description explaining the high-level reason for the pull request]
- Add prop to align pills to the bottom
=> feat: add prop to align pills to the bottom

src/components/Footer/BackToTop.tsx, src/components/Footer/Footer.less, src/components/Footer/Footer.stories.tsx, src/components/Footer/Footer.tsx, src/components/Footer/FooterBanner.tsx, src/components/Footer/FooterCfGov.tsx, src/components/Footer/FooterLinks.tsx, src/components/Footer/SocialMedia.less, src/components/List/List.tsx, src/components/List/ListItem.tsx
Closes #58 
- Distills the CFPB Footer organism so that users simply define the links for each section
- Pulls in styles from CF.gov (social-media.less, footer.less)
1. Check out the netlify deployment
| label | shot|
|---|---|
|CF.gov|![Screen Shot 2023-06-23 at 1 11 24 PM](https://github.com/cfpb/design-stories/assets/2592907/37df27dd-4206-4aba-9251-a9e99f8b0d99)|
|Example|![Screen Shot 2023-06-23 at 1 11 06 PM](https://github.com/cfpb/design-stories/assets/2592907/35d2bddd-123d-4edf-97f7-e9bb6e577fef)|
=> [Component] Footer

.github/CODEOWNERS, .storybook/main.js
Re-enables Storybook autodocs but allows manual MDX overrides if desired for specific components.
See https://github.com/cfpb/design-stories/issues/92
1. Verify the netlify build has an `Overview` section for every component.
=> Re-enable Storybook automatic documentation

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Divider/Divider.stories.tsx, src/components/Divider/Divider.tsx, src/components/Link/Link.less, src/components/Link/Link.stories.tsx, src/components/Link/Link.tsx, src/components/Well/Well.tsx
Closes #95 
- [Component] Well - Make the headerLevel prop optional
- [Component] Divider - created
- [Component] Link - Expand supported variations and create stories
- [Component] Button - support styling as a link
=> Fixes and expansions identified while building Filing Landing page

src/assets/styles/_shared.less
Instead of selectively importing Less rules based on the needs of individual components, import the entire Less stylesheet.
Fixes the issues we found while pairing today.
1. The PR preview should build and look normal.
=> Import the entirety of CFPB's design system

src/components/Divider/Divider.tsx, src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/DropdownInputWithCheckbox.css, src/components/Dropdown/DropdownInputWithCheckbox.tsx, src/components/Dropdown/DropdownPills.less, src/components/Dropdown/DropdownPills.tsx, src/components/Dropdown/utils.tsx, src/components/Icon/Icon.tsx, src/components/Label/Label.tsx, src/components/Layout/LayoutContent.tsx, src/components/Layout/LayoutSidebar.tsx, src/components/Layout/LayoutWrapper.tsx, src/components/Notification/Notification.tsx, src/components/PageHeader/header.less, src/components/Well/Well.tsx
Updates to components to support the scenarios needed for the `Complete User Profile` page.
Closes #74 
- Dropdown
- Updates styling of pills
- Allows customization of pill display location and hiding them
- Allows display of checkbox next to dropdown options
- Allow a 'Clear All' button to quickly clear selections
- Icon
- Display with or without background
- Support propagation of all supported HTML props
- Label
- Hide if no label text provided
- Notification
- Enable show/hide via props
- Enable show/hide icon via props
- [New] Divider component to provide a horizontal rule
- Page Header
- Remove unnecessary margin
- Well
- Code cleanup
1. Open the Netlify preview
2. Visit the Dropdown, Icon, Label stories
3. See if things look sensible
- I hate typescript
=> 74 dropdown redesign

src/components/Navbar/Navbar.stories.tsx, src/components/Navbar/Navbar.tsx
Closes #109 
Skips rendering the built-in Login / Logout links when the expected `user` object is not provided.  This allows consumers of the component to inject customized user auth content via the `links` prop.  
[No User object (Storybook -> Navbar -> No User)](https://deploy-preview-110--cfpb-design-stories.netlify.app/?path=/story/components-navbar--no-user)
["User logged in" via Navbar `user` object](https://deploy-preview-110--cfpb-design-stories.netlify.app/?path=/story/components-navbar--logged-in)
Custom user auth content in SBL Frontend (buttons instead of links)
=> feat: Enable bypass of login/logout to allow customized user auth content

src/components/Banner/Banner.test.tsx, src/components/Banner/Banner.tsx
Closes #113
- update tests
2. yarn vitest Banner
Note: Test says `Tagline` line 14 is untested but there *is* a specific test for that piece of code....so not sure what's going on there.
=> [Banner] Propagate attributes

src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx
Closes #115
- update tests
2. yarn vitest Checkbox
=> [Checkbox] Propagate attributes

src/components/Expandable/Expandable.tsx, src/components/Expandable/ExpandableGroup.tsx
Closes #126
- Pass attributes to wrapper element
2. yarn vitest Expandable
=> [Expandable] Propagate attributes

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.types.tsx, src/components/Dropdown/DropdownPills.tsx, src/components/Dropdown/styles.tsx, src/components/Dropdown/utils.tsx
Closes #119
- update tests
2. yarn vitest Dropdown
=> [Dropdown] Propagate attributes

src/components/Button/Button.test.tsx, src/components/Button/Button.tsx
Closes #111 
- Fixes bug
- Adds test to ensure bug doesn't recur
=> fix: [Button] destructure className from props to avoid overwriting derived classnames

.storybook/main.js, package.json, yarn.lock
Closes #123 
- [CFPB fork of display-element-css created](https://github.com/cfpb/storybook-addon-display-element-css)
- Modified that repo to include the `/dist/` folder so that things would work when installed from Github
- Refactored to search parent element's styles
- Attempts to filter output to only relevant styles
- It kinda works!
=> feat: Add cfpb fork of display-element-css Storybook addon

src/assets/styles/_shared.less, src/components/Expandable/Expandable.stories.tsx, src/components/Expandable/ExpandableGroup.stories.tsx
Closes #120
Apply the width restriction of DS content when displayed in a DS Layout to our Storybook components
- Adds a CSS rule to restrict text element width
- Updates Expandable.stories to use the correct child type
=> fix: Globally restrict width of text content for components when displayed in Storybook

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx
Link #142 
- Apply disabled styles when button is disabled
- Add story for Disabled button
- Removes deprecated "isDisabled" property from Button stories
=> fix: [Button] Apply disabled styles when button is disabled

src/components/Link/Link.less, src/components/Link/Link.stories.tsx, src/components/Link/Link.tsx, src/components/List/List.stories.tsx, src/index.ts
Closes #134
- Avoid underline of icon within a `<Link>` component (https://github.com/cfpb/design-stories/commit/f90d48cda29be0e655aa06cf26c92ec75a3779ba)
- Create new components (`<DestructiveLink>`, `<ListLink>`) to ease creation of these types of Links and update stories to integrate the new components (https://github.com/cfpb/design-stories/commit/ed9380faff595e448c0c27af1746a20b5c5b6a22)
- DestructiveLink
- ListLink
=> Corrections and improvements to Link component

.storybook/preview.js, yarn.lock
Closes #165 
Logo works locally, and worked locally with the previous implementation, but this tries a different way of referencing the logo in hopes that this works once deployed.
Local testing: `yarn build-storybook && npx http-serve ./dist-storybook`
Looks good in [Netlify deployment](https://deploy-preview-166--cfpb-design-system-react.netlify.app/?path=/docs/components-checkbox--overview)
=> fix: Try to fix logo

src/components/Notification/Notification.stories.tsx, src/components/Notification/Notification.test.tsx, src/components/Notification/Notification.tsx, src/components/Notification/NotificationFieldLevel.tsx, src/components/TextInput/TextInput.tsx
Closes #164 
Create the ability to render field-level notifications independently of the TextInput component, so that these notifications can be applied to other types of user input.
- Create a separate NotificationFieldLevel component, which implements a subset of the states from Notification for use at the field-level
- Integrate NotificationFieldLevel into Notification component for ease of use
- Align Notification component docs with Design System
- Integrate updated field-level notification into TextInput component
- Add tests
1. yarn vitest Notification
2. yarn vitest TextInput
=> Field-level notifications

src/components/Headings/Heading.test.tsx, src/components/Headings/Heading.tsx, src/components/Headings/Headings.stories.tsx, src/components/Icon/Icon.stories.tsx, src/index.ts, yarn.lock
Closes #161
- feat: Ability to create `h1` - `h5` elements
- feat: Ability to create "Display heading"
- feat: Ability to create "Eyebrow heading"
- feat: Ability to create "Slug heading"
- feat: Icon w/ Text table on the Icons page
1. yarn vitest Heading
Updated: Sept 29
- I've excluded the `Heading with icon` variant as that was not targeted in #167 
- I did include `slug`, `eyebrow` and `super` because I hadn't realized these were not targeted in #167 until after they were already complete.
=> [Component] Heading

src/components/Checkbox/Checkbox.stories.tsx
Part of #168 
- Make helper text examples say: `(This is optional helper text)`
=> fix: [Checkboxes] Standardize example helper text

src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx, src/components/HelperText/HelperText.tsx, src/components/Radio/Radio.stories.tsx, src/components/Radio/Radio.tsx, src/components/RadioButton/RadioButton.stories.tsx, src/components/RadioButton/RadioButton.test.tsx, src/components/RadioButton/RadioButton.tsx, src/index.ts
Closes #187 
- Updates Storybook text to match Checkbox format
- Adds intro paragraph and corrects `Source` link
- Renames component from `Radio` to `RadioButton` for clarity
- Renames the `isDisabled` prop to match the HTML standard `disabled` instead
- Creates a HelperText component to easily and consistently apply the appropriate styles
- Scope creep: Integrates HelperText into the Checkbox component
1. yarn vitest Radio
=> [Component] Radio buttons

src/components/Notification/NotificationFieldLevel.tsx
Closes #178 
The default TextInput story was showing an error, this addresses that situation. 
|Before|After|
|---|---|
|![Before](https://github.com/cfpb/design-system-react/assets/2592907/7f3ac783-64ed-4d51-b635-d667a681b857)|![After](https://github.com/cfpb/design-system-react/assets/2592907/c0eee35c-1964-40be-9142-975274dacb6b)|
=> fix: Hide notification if there is no text content

src/components/Dropdown/Dropdown.test.tsx
Let's get those tests passing again! ✅
- skip broken tests until refactor is done
1. Are the tests passing?
=> test(dropdown): skip broken tests

src/components/Headings/Heading.test.tsx, src/components/Headings/Heading.tsx, src/components/Headings/Headings.stories.tsx
Closes #203 
No visual change, just a structural change in how the heading is implemented to improve accessibility (no longer displaying an h5 ahead of an h1)
|Before|After|
|---|---|
|<img width="207" alt="eyebrow-before" src="https://github.com/cfpb/design-system-react/assets/2592907/bb0e6020-2207-4394-af45-5a9f6c7399ce">|<img width="195" alt="eyebrow-after" src="https://github.com/cfpb/design-system-react/assets/2592907/da263166-f9c1-4996-9dae-ad6bfd231981">|
=> fix: [Eyebrow] display as <div> with ".h5" class instead of <h5>

src/components/Tagline/Tagline.stories.tsx
I went through and [verified the Tagline component](https://github.com/cfpb/design-system-react/issues/205) as part of the work on the banner component. Only small changes to the documentation appear to be needed. I didn't add the deprecated "Extra large tagline" story from the design system, since it was deprecated and all, but we can chat about that at the DSR sync. 
- add component description
- remove heading
- change stories to sentence case
1. Take a peek at the DSR and see how it looks
I didn't mark this component as "verified" in this PR, since I'm not sure if we have an official stamp of approval process yet, so I'll hold off till at least we chat about it at the sync.
=> docs(tagline): modify docs to verify component

src/assets/styles/_shared.less
Closes #214 
- Make code blocks' font white
- Increase code blocks' font size
- Increase code blocks' line height
1. Visit [deployed preview](https://deploy-preview-220--cfpb-design-system-react.netlify.app/?path=/docs/components-draft-taglines--overview)
1. Click `Show Code` for a Story
2. Observe
- There's a [two year old issue in Storybook](https://github.com/storybookjs/storybook/issues/9641) to enable users to change the theme used for syntax highlighting but it doesn't have much traction, so this is our workaround.
=> fix: [Storybook] Improve readability of code blocks

.github/CODEOWNERS
Closes #226 
PRs approved by Bill are blocked until he gets added as a CODEOWNER. 
We'll probably have to disable that rule, merge this PR, then re-enable it.
=> Add Bill as codeowner

src/components/Link/Link.less, src/components/Link/Link.stories.tsx, src/components/Link/Link.test.tsx, src/components/Link/Link.tsx
Link to #215 
- Sync story content with DS
- Add unit tests
1. yarn vitest Link
- Accessibility issue with the Icon component, which is used in some of the Link stories, due to missing alt text.  I think this issue should be addressed as part of the Icon component's verification process.
=> [Link] Address issues identified during the verification process 

.storybook/main.js, package.json, vite.config.ts, yarn.lock
Chromatic's TurboSnap feature has been failing for awhile now, or perhaps never worked correctly? This small PR dug around to figure out why, and it looks like it's a problem with the creation of the `preview-stats.json` file. The passed command line option `--webpack-stats-json` to `build-storybook` in the `package.json` appears to be correct for webpack not vite. This PR uses [Chromatic's recommended plugin](https://www.chromatic.com/docs/turbosnap/#github-pullrequest-triggers:~:text=(for%20experimental%20Vite,)) `vite-plugin-turbosnap` to create the stats file. Take a look at the screenshots and commits for a history of attempted solutions.
Resolves issue #219 
- removes dead code `--webpack-stats-json` from `build-storybook`
- add and configure `vite-plugin-turbosnap`
This PR fixes …
=> fix(chromatic): generate webpack-stats.json with vite

src/components/Link/Link.stories.tsx, src/components/Link/Link.tsx
Closes #215 
This PR is to get the Design team's (@natalia-fitzgerald) final approval. 
@billhimmelsbach @shindigira Please ignore
- Moves Link component to Verified status
=> design(Link): final design review for Link component

src/components/Link/Link.stories.tsx
Closes #215 
@natalia-fitzgerald Final adjustment to the Links documentation. 
@billhimmelsbach @shindigira Please ignore.
- Remove the `Print links` example
=> fix: [Links] Remove Print example

.storybook/manager.js, src/components/Banner/Banner.stories.tsx, src/components/Banner/Banner.tsx
Makes changes to Banner (US gov) to move to verified.
Note: Made the default tagline for the Banner (US gov) [match the text and markup](https://github.com/cfpb/design-system-react/pull/246/files#diff-f9882edc8324cf88b43076801e6c25a605f41b89e1e3bf19a04c7eb2c05619a7R40) of the banner displayed in the DS. This better matches the DS, and avoids having to remember to wrap the "United States government" part of the tagline in a span with class `u-nowrap` in the instances it occurs.
Closes #213 
**- Note: the design system only includes one use case without links, our examples in the DSR also include one with generic links and one with the implementation on cf.gov**
- ~[ ] All steps for existing components plus the following steps~
- ~[ ] The new component has been added to the CFPB Design …
=> design(banner): final design review for Banner (US gov)

src/components/TextIntroduction/TextIntroduction.stories.tsx, src/components/TextIntroduction/TextIntroduction.test.tsx, src/index.ts
Closes #248 
- Fixes an error that was introduced during git conflict resolution.  
- Import component from root `index.ts` to ensure it is correctly exposed to end users.
=> fix: [TextIntroduction] Export component from /src/index

src/components/Buttons/Buttons.stories.tsx
Closes #252 
- Remove responsive styling from Destructive Action
1. Visit [Button](https://deploy-preview-253--cfpb-design-system-react.netlify.app/?path=/story/components-verified-buttons--destructive-action)
2. Use your preferred method to view the page at a mobile width. 
3. Observe that buttons stay inline, provided there is horizontal space to accommodate their content.
=> [Button] Keep destructive action inline on mobile

src/components/Pagination/usePagination.test.tsx, src/components/Pagination/usePagination.tsx
Closes #266
- Update defaults from `usePagination` to use the `MIN_PAGE` value instead of `0`
1. yarn test Pagination
2. yarn test Table
`Before` pagination showed that we were on page `0 of 0`, `After` we see page `1 of 1` which feels more reasonable. 
|Before|After|
|---|---|
|![Screenshot 2023-12-05 at 10 07 25 AM](https://github.com/cfpb/design-system-react/assets/2592907/bc0dcce4-dd2e-4825-bccf-c5168965b378)|![Screenshot 2023-12-05 at 10 07 38 AM](https://github.com/cfpb/design-system-react/assets/2592907/2173d5b2-e31c-4dd0-a358-008190ec26e3)|
=> fix: More sensible usePagination defaults

src/components/Layout/Layout.tsx, src/components/Layout/layout.less
Closes #270
- Removes negative margin-right that was causing sidebar overflow
- The overflow of the sidebar's `border` (yellow portion in the screenshots) matches what we see in the Design System, so I've left that unchanged. 
|Layout|Before|After|
|---|---|---|
|1-3|![1-3-before](https://github.com/cfpb/design-system-react/assets/2592907/6638800f-f0d4-4252-b8fa-b722ddc2c149)|![1-3-after](https://github.com/cfpb/design-system-react/assets/2592907/f2ce5ee7-d226-4616-9bfd-fe1625573453)|
|2-1|![2-1-before](https://github.com/cfpb/design-system-react/assets/2592907/14bb1077-4015-45ea-8b49-08386077a59c)|![2-1-after](https://github.com/cfpb/design-system-react/assets/2592907/0cfd2a7c-84cd-497b-b2c6-c72a7fedac36)|
=> fix: [Layout] Remove negative margin-right that was causing sidebar overflow

src/components/Link/Link.stories.tsx, src/components/Link/Link.tsx, src/index.ts, vite.config.ts
Well this took some experimentation, but we got there. Allows `Link` to use a `isRouterLink` prop to convert them to `react-router` links with minimal hassle.
- add `react-router-dom` as an external dependency in the vite config, since `react-router` needs its links to share the same instance of the library to work. Works in concert [with this change](https://github.com/cfpb/sbl-frontend/compare/198-integrate-react-router-links?expand=1#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddR26-R28) in `sbl-frontend`. What a pain this was. (Also, I added a maybe missing `react-dom` from the `optimizeDeps.exclude` array for good measure)
- add a `isRouterLink` prop that switches `Link` to using `react-router` Links
- fixes some Typescript errors
- adds a story for …
=> feat(Link): add react-router link integration

src/index.ts
:doh: I didn't make the component accessible to the world!
=> fix: Export TextArea component from DSR library

src/components/Hero/Hero.tsx
Closes #309 
As we use Hero in more scenarios we find the need for expanded support of what types of content can be passed to these props.
=> fix: [Hero] Allow React elements to be passed to the `heading` and `subheading` props

src/index.ts
I'd like to add skip links from the DSR to the `sbl-frontend` project, but we're currently not exporting them.
- adds an export for skip links
1. Can you now import skip links from the DSR?
- there are some additional focus styles that we might want to import over later
=> fix(skip-link): add to exports

src/components/Footer/BackToTop.tsx, src/components/Footer/FooterCfGov.tsx, src/components/Icon/Icon.tsx
Currently we use `alt` as the accessibility feature on `Icon`s that serve as images with the role `img`, but `alt` [isn't quite right for a `svg`](https://accessibilityinsights.io/info-examples/web/svg-img-alt/). So we have a couple options, and we can pick one of these depending on the use case: 
Instead of `alt`, the `svg` should have one of these:
- a `<title>` + `<description>` as a child of the `<svg>` 
- the `svg` could have an `aria-labelledby` and an optional `aria-describedby`
- just an `aria-label`  for simple `svg`s 
I'd prefer to use title/description, but it would be tricker to manipulate/inject that into the raw html that this component relies on. I've allowed `aria-labelledby` and an optional `aria-describedby` in case people want them for more complicated `svg`s, but …
=> feat(icon): add aria-label, aria-labelledby, aria-describedby, isPresentational

src/components/Hero/Hero.test.tsx, src/components/Hero/Hero.tsx
A little bit of a nuanced issue here that affects accessibility. Right now, if I wanted the heading of a hero to be a `<h1>` instead of a `<p>` tag, I could pass in the full node instead of the text:
Instead of this: 
`heading={My super cool heading!}`
Do this: 
`heading={<h1>My super cool heading!</h1>}`
The problem with that is that then the heading still renders inside of a `<p>` tag, which isn't great, but also the stylings of the heading wouldn't get applied to the heading but instead get applied to the enclosing `<p>` tag.
So this PR instead allows the `headingLevel` to create a heading with the `heading` content directly, instead of being wrapped in a `<p>` tag. This lets you set the `heading` to be an `<h1>` or other heading level a little easier, which we'll want for …
=> fix(hero): let headingLevel dictate the heading tag without enclosing <p> tag

src/components/SkipNav/SkipNav.less
A very small change to add the focus ring in for skip links like it appears on consumerfinance.gov. There are other styles we could add from there potentially in the future, but the focus ring is the one that matter for accessibility, so I would like to prioritize this small change first.
- adds in focus ring as per consumerfinance.gov 's example
1. Does this add a focus ring to the skip link?
_Before_
_After_
_Example from consumerfinance.gov_
- we can enhance this component's styling more in the future with the fancier transition from consumerfinance.gov, etc. but for now let's get the necessary accessible parts in ASAP
=> fix(skip-link): add focus ring

src/components/PageHeader/PageHeader.tsx
Small change to make the header be wrapped in a semantic tag of `header` instead of a `div` for accessibility
- change `div` to `header`
=> fix(page-header): change html to semantic header instead of div

src/components/Headings/Heading.tsx, src/components/Paragraph/Paragraph.tsx, src/components/TextIntroduction/TextIntroduction.tsx, src/stories/Introduction.stories.mdx
Close #338 
On SBL we have some descriptions that include lists (Errors page: download and upload links).  I'm seeing console errors about nesting `ul`s within paragraphs. 
This PR basically renders `description` within a `<p>` tag if it's a string, otherwise renders it unchanged allowing us to pass more customized content.
=> feat: [TextIntroduction] Support ReactNode content in the `description`

src/components/Navbar/Navbar.tsx, src/components/PageHeader/PageHeader.test.tsx, src/components/PageHeader/PageHeader.tsx
Currently, the CFPB logo in the React DS has a hardcoded href pointing to cf.gov. Using the CFPB logo from the React DS, we've run into the issue of users being booted from the Metro2 tool when the logo is clicked. This will inevitably cause frustration and confusion, as users will expect to be routed back to the landing page for the Metro2 Evaluator Tool. 
This PR seeks to implement a change which will turn the logo href into a prop that can be defined in every project that uses the React DS component. Additionally, the logo still defaults to cf.gov if no other href/url is specified. 
- href prop created for CfpbLogo, passed to Navbar and PageHeader
- test file created for page header to include testing custom href and/or defaulting to cf.gov
1. Pull branch and run `yarn start`. Navigate …
=> Create Declarable CFPB Logo href

src/components/Headings/Heading.tsx, src/components/Paragraph/Paragraph.tsx
The oldest components in the library appear to be using ReactNode instead of JSX.Element. This should fix some of the weird linting errors in repos that use the DSR
- changes ReactNode to JSX.Element for paragraph and headings
1. Linting errors should go away when these components are used.
=> fix(typescript): remove old ReactNode types

src/components/PageHeader/PageHeader.test.tsx, src/components/PageHeader/PageHeader.tsx, src/components/PageHeader/header.less
In support of https://github.com/cfpb/sbl-frontend/issues/514
- Enable the removal of the bottom border via prop
- Add unit test
1. yarn test PageHeader
=> feat: [PageHeader] Enable/disable bottom border

src/components/Pagination/Pagination.tsx, src/components/Table/Table.tsx
Accessibility improvement
- [Table] Propagate Table id to Pagination component
- [Pagination] Utilize `tableId` to uniquely identify and label Pagination's input element
1. Load paginated table in an application (couldn't get ANDI to recognize the error in Storybook)
2. Run [ANDI](https://www.ssa.gov/accessibility/andi/help/install.html) accessibility tool
3. Verify that it doesn't identify the following error
- `Element nested in <label> but label[for=m-pagination_current-page] does not match element [id=m-pagination_current-page-default`
|ANDI Before|ANDI After|
|---|---|
|![Screenshot 2024-05-24 at 3 32 30 PM](https://github.com/cfpb/design-system-react/assets/2592907/cab51fd4-d9ae-467f-be96-78fcb006d434)|![Screenshot 2024-05-24 at 3 29 …
=> fix: [Table] Pagination input label's 'for' property  needs to align with the input id

src/components/Alert/Alert.test.tsx, src/components/Icon/Icon.test.tsx, src/components/Icon/Icon.tsx
- I've confirmed that upgrading to the latest `cfpb-icons` library is the source of the breakage, causing the `updating` icons to no longer be animated
- I've confirmed that other icon modifiers (ex. [Success alert icon shown in green](https://deploy-preview-364--cfpb-design-system-react.netlify.app/?path=/story/components-draft-alerts--success)) seem to be working as expected.
1. Visit https://deploy-preview-364--cfpb-design-system-react.netlify.app/?path=/story/components-draft-icons--status-icons
1. Confirm that the `updating` icon is animated
=> fix(Icon): Use BEM for Icon modifier classes

src/components/Navbar/Navbar.stories.tsx, src/components/Navbar/Navbar.tsx, src/components/Navbar/navbar.less, src/components/PageHeader/header.less
Made Navbar responsive and updated styles to match Figma designs
=> Navbar-update

src/components/Footer/FooterCfGov.tsx
Updated link address to https://oig.federalreserve.gov/
=> Updated OIG footer link address

src/components/Alert/Alert.tsx, src/components/Alert/AlertFieldLevel.tsx, src/components/Alert/AlertLink.tsx
Often information is conveyed by the icons of our alerts (this is an error or warning, is this an external link) that is not conveyed explicitly by the text. These icons are then not presentational, and should be labeled.
- Explicitly adds aria-labels to svgs in alerts, field level alerts, and alert links
- removes `alt` text in favor of `aria-label` since alt text is not universally supported on svg elements (changes to the Icon element's use of alt text will be in a follow-up PR)
1. Are the svgs now properly labeled on alerts, field level alerts, and alert links?
=> fix(a11y): add explicit labels to alert icons

src/components/TextInput/TextInput.tsx
[Short description explaining the high-level reason for the pull request]
- TextInput.tsx: Updated the property typing to fix an issue which caused properties that should be optional, to be considered mandatory instead.
1. View and verify the the deploy preview
2. Pull **308-ts-error-fix**
3. Run **yarn lint** against the branch
4. Verify that **TextInput.tsx** has no errors
5. Run **yarn test** against the branch and verify that everything passes
6. Build the package
7. Update the **package.json** in **sbl-frontend** to include **"design-system-react": "file:./<path-to-package.tgz>/package.tgz"**
8. Run **yarn install**
9. Pull **986-default-max-length** in **sbl-frontend**
10. Verify that **TextInput.tsx** in **sbl-frontend** has no errors
=> [TextInput] Certain props should be optional

src/components/Alert/Alert.stories.tsx, src/components/Alert/Alert.test.tsx, src/components/Alert/Alert.tsx
Currently when there's no message but has children (explanations), then a `m-notification_explanation` applied which makes it not possible to achieve designs like these (unbolded, aligned text):
- if there is no message, but still has children then do not apply `m-notification_explanation` to allow alert flexibility
1. Do the tests pass?
2. How do the examples look?
3. Try modifying the package.json to point the DSR to this commit and see how the alerts are affected.
=> fix(alert): no wrapper class when no message provided

src/components/Alert/Alert.css, src/components/Alert/Alert.stories.tsx
Close #386
Close #387 
- feature: Restrict width of Alert explanation text to 670px
- fix: Allow icons within field-level Alert content (i.e. external links) to display inline and color-matched
- stories: Better align Story content of DSR with DS examples, while also demonstrating the unique capabilities of DSR
Review the [preview deployment](https://deploy-preview-388--cfpb-design-system-react.netlify.app/?path=/docs/components-draft-alerts--overview)
=> [Alert] Width restriction; Icon positioning and coloring
