package.json

I have added this repo to our netlify account. Let's see if it builds this pull request and posts a comment.
See: https://github.localreg-tech/sbl-data-collection/issues/401

Configure netlify deploy previews

---

.vscode/settings.json
README.md
package.json
src/components/Dropdown.stories.tsx
src/components/Dropdown.tsx
yarn.lock

Huge thanks to @the-raft-oar for straightening out those Type conflicts!!!
Dropdown input that supports multi-select.  
- [Single select](https://deploy-preview-15--cfpb-design-stories.netlify.app/?path=/story/components-dropdown--default-dropdown)
- [Mutli-select](https://deploy-preview-15--cfpb-design-stories.netlify.app/?path=/story/components-dropdown--multi-select)

[Components] Dropdown w/ Multi-select

---

src/components/Label.test.tsx
src/components/Label.tsx

Closes #39 
- Clean up application of class names
- Add tests

[Test] Label

---

package.json
src/components/Radio.stories.tsx
src/components/Radio.test.tsx
src/components/Radio.tsx
vite.config.ts
yarn.lock

Closes #41 
- Adds tests
- Addresses some ESLint issues

[Test] Radio

---

src/components/TextInput.test.tsx
src/components/TextInput.tsx

Closes #44
- Fix eslint issues
- Add tests

[Test] Textinput

---

src/components/Notification.test.tsx
src/components/Notification.tsx
src/components/NotificationLink.tsx

Closes #38 
- Cleanup eslint errors
- Adds tests

[Test] Notification

---

src/index.ts

Closes #62
- Export new components in `src/index.ts`

feat: Expose the newly available components since last release

---

src/components/Table/TableSimple.test.tsx
src/components/Table/TableSimple.tsx

[Short description explaining the high-level reason for the pull request]
- add tests to TableSimple

fix: add tests to TableSimple

---

src/components/Pagination/Pagination.test.tsx

[Short description explaining the high-level reason for the pull request]
- Add pagination tests

add pagination tests

---

src/components/Divider/Divider.test.tsx
src/components/Divider/Divider.tsx

Closes #117 
- Code cleanup
- Add tests

[Divider] Add tests

---

src/components/Hero/Hero.test.tsx
src/components/Hero/Hero.tsx

Closes #133
- Create tests
2. yarn vitest Hero

[Hero] Propagate attributes

---

src/components/Button/Button.test.tsx
src/components/Button/Button.tsx

Closes #111 
- Integrate passed classnames into existing classname derivation logic
- Update tests
- Cleanup tests
- Ensure 100% test coverage
2. yarn vitest Button

[Button] Propagate attributes

---

src/components/Navbar/navbar.less

Closes #122 
- Apply letter-spacing to nav links
- Update username font-size & line-height

fix: [Navbar] Match design specs

---

.storybook/preview.js
src/components/Checkbox/Checkbox.docs.mdx
src/components/Checkbox/Checkbox.stories.tsx
src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx
yarn.lock

Part of #141 
Enables us to force Checkbox components to display various states (focused, hovered)
- Add new prop `inputClassName` to `<Checkbox />` to allow targeted classname on `input` element
- Update docs to leverage new prop
- Adds the `disabled selected` state to both sections
- Adds unit test for `inputClassName`
|Type|Before|After|
|---|---|---|
|Standard|<img width="284" alt="Screenshot 2023-09-06 at 12 14 52 PM" src="https://github.com/cfpb/design-system-react/assets/2592907/279935ff-8ea9-4993-a02d-8f2e8bc6e19b">|<img width="290" alt="Screenshot 2023-09-06 at 12 14 25 PM" src="https://github.com/cfpb/design-system-react/assets/2592907/5e689994-c71c-42d2-ab66-4136e4590dbe">|
|Large|<img width="716" alt="Screenshot 2023-09-06 at 12 15 02 PM" …

[Checkbox] Fix display of various states

---

src/components/Hero/Hero.stories.tsx

Closes #169
- fix: Update title to `Heroes` from `Hero`
- feat: Add intro paragraph
- fix: Update variant name to `50/50` from `Fifty Fifty`
- fix: Update variant name to `With knockout text` from `Knockout`
- fix: Update variant name to `With photograph` from `With photo`
1. Open netlify deployment
2. Verify things look good

fix: Update language to better align with Design System docs

---

src/components/Headings/Heading.tsx

Closes #195 
- Add correct DS css class

fix: [Slug] Add green bar

---

package.json
yarn.lock

- update [design system to v0.32.0 ](https://www.npmjs.com/package/@cfpb/cfpb-design-system)
1. Are the new changes to the design system reflected in storybook?

deps(design-system): update to v0.32.0

---

README.md

docs: Add instructions for integrating updates to CFPB DS

---

src/components/Navbar/Navbar.tsx
src/components/Navbar/navbar.less

Updated navbar styles to match latest design updates

578-navbar-link-updates

---

.github/CODEOWNERS

Adding @ojbravo to the CODEOWNERS file for the DSR. 🥳
- adds Omar Bravo to the CODEOWNERS file
1. Is Omar added to future PRs automatically?

chore(codeowners): add Omar Bravo
